### ISSUE TITLE
cv2.imgshow() not working

### ISSUE THREAD

**Issue by MarioGK** [SciSharp/SharpCV#21]
When you call the function it throws this error:
```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at SharpCV.cv2_native_api.highgui_imshow(String winName, IntPtr mat)
   at SharpCV.cv_api.imshow(String windownName, Mat img)
```

Example:
![image](https://user-images.githubusercontent.com/8379079/147985525-421b8e05-115a-42f6-acf8-4fc602535ec0.png)

**Comment by gkapellmann** [comment]
I am getting the same problem.
